steps:
  # Pull the previous image to use as cache source
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'us-central1-docker.pkg.dev/ai-subs-poc/ai-subs-repo/ai-subs-backend:latest']
    allowFailure: true
  # Build using the previous image as layer cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from=us-central1-docker.pkg.dev/ai-subs-poc/ai-subs-repo/ai-subs-backend:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/ai-subs-poc/ai-subs-repo/ai-subs-backend:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ai-subs-poc/ai-subs-repo/ai-subs-backend:latest']
images:
  - 'us-central1-docker.pkg.dev/ai-subs-poc/ai-subs-repo/ai-subs-backend:latest'
timeout: '2700s'
options:
  machineType: 'E2_HIGHCPU_8'
