import { useState, useEffect, useRef } from "react";
import { ChevronDownIcon } from "@heroicons/react/24/outline";
import { useSpring, animated, config, useTransition } from "react-spring";
import { API_BASE_URL } from "../../../config";
import { formatScreenshotUrl } from "../../../utils/url";
import { DraggableImageModal } from "../../common/DraggableImageModal";

interface SummarySection {
  title: string;
  start: string;
  end: string;
  summary: string;
  screenshot_url?: string | null;
}

interface SummaryPanelProps {
  isVisible: boolean;
  onSeekTo?: (time: string) => void;
  summaries: SummarySection[];
  setSummaries: React.Dispatch<React.SetStateAction<SummarySection[]>>;
  loading: boolean;
  generateSummaries: () => Promise<void>;
  videoHash?: string | null;
}

// Animated Accordion Content Component
const AccordionContent = ({
  children,
  isOpen,
}: {
  children: React.ReactNode;
  isOpen: boolean;
}) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const style = useSpring({
    from: { height: 0, opacity: 0 },
    to: {
      height: isOpen ? contentRef.current?.scrollHeight || "auto" : 0,
      opacity: isOpen ? 1 : 0,
    },
    config: config.stiff,
  });

  return (
    <animated.div style={{ ...style, overflow: "hidden" }}>
      <div ref={contentRef}>{children}</div>
    </animated.div>
  );
};

// Chevron Component
const Chevron = ({ rotation }: { rotation: number }) => {
  const style = useSpring({
    transform: `rotate(${rotation}deg)`,
    config: { tension: 300, friction: 20 },
  });

  return (
    <animated.div style={style}>
      <ChevronDownIcon className="h-5 w-5 text-gray-500" />
    </animated.div>
  );
};

export const SummaryPanel = ({
  isVisible,
  onSeekTo,
  summaries,
  setSummaries,
  loading,
  generateSummaries,
  videoHash,
}: SummaryPanelProps) => {
  const [expandedSection, setExpandedSection] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalImageUrl, setModalImageUrl] = useState<string | null>(null);
  const [screenshotLoading, setScreenshotLoading] = useState(false);
  const hasAutoGeneratedRef = useRef(false);

  // Regenerate screenshots for existing video
  const regenerateScreenshots = async () => {
    if (!videoHash) {
      setError("Video hash not available");
      return;
    }

    setScreenshotLoading(true);
    setError(null);

    try {
      const response = await fetch(
        `${API_BASE_URL}/regenerate_screenshots/${videoHash}`,
        { method: "POST" }
      );

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(
          errorData.detail || `Failed to regenerate screenshots: ${response.status}`
        );
      }

      const data = await response.json();

      // Update summaries with new screenshot URLs
      if (data.updated_sections && Array.isArray(data.updated_sections)) {
        setSummaries((prevSummaries) =>
          prevSummaries.map((summary) => {
            const updated = data.updated_sections.find(
              (s: { title: string; screenshot_url: string }) =>
                s.title === summary.title
            );
            return updated
              ? { ...summary, screenshot_url: updated.screenshot_url }
              : summary;
          })
        );
      }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to regenerate screenshots"
      );
    } finally {
      setScreenshotLoading(false);
    }
  };

  // List transition animation
  const transitions = useTransition(summaries, {
    from: { opacity: 0, transform: "translate3d(0, 20px, 0)" },
    enter: { opacity: 1, transform: "translate3d(0, 0px, 0)" },
    keys: (item) => item.start + item.end,
    trail: 100, // Stagger effect
  });

  // Auto-generate summaries when panel opens if none exist
  useEffect(() => {
    if (
      isVisible &&
      !summaries.length &&
      !loading &&
      !error &&
      !hasAutoGeneratedRef.current
    ) {
      hasAutoGeneratedRef.current = true;
      generateSummaries();
    }
  }, [isVisible, summaries.length, loading, error, generateSummaries]);

  const handleSeekTo = (time: string) => {
    if (onSeekTo) {
      onSeekTo(time);
    }
  };

  const openImageModal = (imageUrl: string | undefined) => {
    if (imageUrl) {
      setModalImageUrl(imageUrl);
      setIsModalOpen(true);
    }
  };

  if (!isVisible) return null;

  return (
    <div className="surface-panel flex flex-col h-full">
      <div
        className="px-4 sm:px-5 py-3 border-b flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2"
        style={{ borderColor: 'var(--border-subtle)' }}
      >
        <h3 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
          Content Summary
        </h3>
        {(!summaries.length || summaries.length > 0) && !loading && !screenshotLoading && (
          <div className="flex flex-wrap gap-2">
            {!summaries.length ? (
              <button
                onClick={generateSummaries}
                className="btn-primary text-xs"
                aria-label="Generate content summary"
              >
                Generate Summary
              </button>
            ) : (
              <>
                <button
                  onClick={regenerateScreenshots}
                  disabled={!videoHash}
                  className="btn-tonal"
                  title={!videoHash ? "Video hash not available" : "Regenerate screenshots from video"}
                  aria-label="Regenerate screenshots"
                >
                  Regenerate Screenshots
                </button>
                <button
                  onClick={generateSummaries}
                  className="btn-tonal"
                  aria-label="Regenerate content summary"
                >
                  Regenerate Summary
                </button>
              </>
            )}
          </div>
        )}
      </div>

      {loading && (
        <div className="flex flex-col items-center justify-center flex-1 p-8 text-center" role="status" aria-live="polite">
          <span className="spinner spinner-lg mb-4" aria-hidden="true" />
          <p className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
            Generating summary…
          </p>
          <p className="text-xs mt-1.5 max-w-sm" style={{ color: 'var(--text-tertiary)' }}>
            Analyzing video content and extracting key points
          </p>
        </div>
      )}

      {screenshotLoading && (
        <div className="flex flex-col items-center justify-center flex-1 p-8 text-center" role="status" aria-live="polite">
          <span className="spinner spinner-lg mb-4" aria-hidden="true" />
          <p className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
            Regenerating screenshots…
          </p>
          <p className="text-xs mt-1.5 max-w-sm" style={{ color: 'var(--text-tertiary)' }}>
            Extracting frames from video and uploading to storage
          </p>
        </div>
      )}

      {!loading && !screenshotLoading && summaries.length === 0 && !error && (
        <div className="empty-state flex-1">
          <svg
            className="empty-state-icon"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
            />
          </svg>
          <h3 className="text-sm font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>
            No summary yet
          </h3>
          <p className="text-xs mb-6 max-w-sm leading-relaxed" style={{ color: 'var(--text-tertiary)' }}>
            Generate a summary for a quick overview of key topics and segments.
          </p>
          <button
            onClick={generateSummaries}
            className="btn-primary"
            aria-label="Generate content summary"
          >
            Generate Summary
          </button>
        </div>
      )}

      {error && !loading && (
        <div
          className="mx-4 sm:mx-5 my-4 p-3 rounded-md"
          style={{
            background: 'oklch(65% 0.20 25 / 0.10)',
            border: '1px solid oklch(65% 0.20 25 / 0.30)',
          }}
          role="alert"
          aria-live="assertive"
        >
          <div className="flex items-start gap-3">
            <svg
              className="w-5 h-5 flex-shrink-0 mt-0.5"
              style={{ color: 'var(--c-error)' }}
              fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <div className="flex-1">
              <p className="text-sm font-medium" style={{ color: 'var(--c-error)' }}>{error}</p>
              <button
                className="mt-2 text-xs underline focus:outline-none rounded"
                style={{ color: 'var(--c-error)' }}
                onClick={() => setError(null)}
                aria-label="Dismiss error message"
              >
                Dismiss
              </button>
            </div>
          </div>
        </div>
      )}

      {!loading && summaries.length > 0 && (
        <div
          className="overflow-y-auto flex-1"
          style={{ borderTop: '1px solid var(--border-subtle)' }}
        >
          {transitions((style, section, _, index) => (
            <animated.div
              style={style}
              className="border-b transition-colors hover:[background:var(--bg-subtle)]"
            >
              <div
                className="flex flex-col sm:flex-row items-start gap-3 sm:gap-4 px-4 sm:px-5 py-4"
                style={{ borderColor: 'var(--border-subtle)' }}
              >
                {section.screenshot_url ? (
                  <div className="flex-shrink-0 w-full sm:w-24">
                    <img
                      src={formatScreenshotUrl(section.screenshot_url)}
                      alt={`Screenshot for ${section.title}`}
                      className="w-full sm:w-24 h-24 object-cover rounded-md transition-all duration-200 cursor-pointer hover:scale-105 border"
                      style={{ borderColor: 'var(--border-subtle)' }}
                      onClick={(e) => {
                        e.stopPropagation();
                        openImageModal(formatScreenshotUrl(section.screenshot_url));
                      }}
                      role="button"
                      tabIndex={0}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' || e.key === ' ') {
                          e.preventDefault();
                          openImageModal(formatScreenshotUrl(section.screenshot_url));
                        }
                      }}
                      aria-label={`View full screenshot for ${section.title}`}
                    />
                  </div>
                ) : (
                  <div
                    className="flex-shrink-0 w-full sm:w-24 h-24 rounded-md flex items-center justify-center border"
                    style={{
                      background: 'var(--bg-subtle)',
                      borderColor: 'var(--border-subtle)',
                    }}
                  >
                    <span className="text-xs" style={{ color: 'var(--text-tertiary)' }} aria-label="No preview available">[No preview]</span>
                  </div>
                )}

                <div
                  className="flex-1 min-w-0 cursor-pointer"
                  onClick={() => setExpandedSection(expandedSection === index ? null : index)}
                  role="button"
                  tabIndex={0}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      setExpandedSection(expandedSection === index ? null : index);
                    }
                  }}
                  aria-expanded={expandedSection === index}
                  aria-label={`${expandedSection === index ? 'Collapse' : 'Expand'} section: ${section.title}`}
                >
                  <div className="flex justify-between items-start gap-2">
                    <h4 className="text-sm font-semibold leading-snug" style={{ color: 'var(--text-primary)' }}>
                      {section.title}
                    </h4>
                    <div className="flex-shrink-0 rounded-full p-1 transition-colors hover:[background:var(--bg-subtle)]">
                      <Chevron rotation={expandedSection === index ? 180 : 0} />
                    </div>
                  </div>

                  <p
                    className="mt-1.5 text-xs font-mono tabular-nums"
                    style={{ color: 'var(--text-tertiary)' }}
                  >
                    {section.start} – {section.end}
                  </p>

                  <div
                    className={`mt-2 text-sm leading-relaxed overflow-hidden transition-all duration-300 ease-in-out ${
                      expandedSection === index ? "opacity-0 h-0" : "opacity-100"
                    }`}
                    style={{ color: 'var(--text-secondary)' }}
                  >
                    <p className="line-clamp-2">{section.summary}</p>
                  </div>
                </div>

                <div className="flex-shrink-0 self-start">
                  <button
                    className="btn-tonal flex items-center gap-1.5"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleSeekTo(section.start);
                    }}
                    aria-label={`Jump to ${section.title} at ${section.start}`}
                  >
                    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span className="hidden sm:inline">Jump</span>
                  </button>
                </div>
              </div>

              <AccordionContent isOpen={expandedSection === index}>
                <div
                  className="px-4 sm:px-5 py-3 border-t"
                  style={{
                    background: 'var(--bg-subtle)',
                    borderColor: 'var(--border-subtle)',
                  }}
                >
                  <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                    {section.summary}
                  </p>
                </div>
              </AccordionContent>
            </animated.div>
          ))}
        </div>
      )}

      {/* Image Modal */}
      {isModalOpen && modalImageUrl && (
        <DraggableImageModal
          imageUrl={modalImageUrl}
          onClose={() => setIsModalOpen(false)}
        />
      )}
    </div>
  );
};
