import { useState, useEffect, useRef } from "react";
import { ChevronDownIcon } from "@heroicons/react/24/outline";
import { useSpring, animated, config, useTransition } from "react-spring";
import { API_BASE_URL } from "../../../config";

interface SummarySection {
  title: string;
  start: string;
  end: string;
  summary: string;
  screenshot_url?: string | null;
}

interface SummaryPanelProps {
  isVisible: boolean;
  onSeekTo?: (time: string) => void;
  summaries: SummarySection[];
  setSummaries: React.Dispatch<React.SetStateAction<SummarySection[]>>;
  loading: boolean;
  generateSummaries: () => Promise<void>;
  videoHash?: string | null;
}

// Simple Image Modal Component
interface ImageModalProps {
  imageUrl: string;
  onClose: () => void;
}

const ImageModal: React.FC<ImageModalProps> = ({ imageUrl, onClose }) => {
  // Prevent closing modal when clicking on the image itself
  const handleImageClick = (e: React.MouseEvent) => {
    e.stopPropagation();
  };

  return (
    <div
      className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4"
      onClick={onClose} // Close when clicking backdrop
    >
      <div
        className="relative bg-white p-2 rounded-lg shadow-xl max-w-6xl max-h-[90vh]"
        onClick={handleImageClick} // Prevent closing on image container click
      >
        <img
          src={imageUrl}
          alt="Enlarged screenshot"
          className="block w-[900px] max-h-[85vh] object-contain rounded-xl"
        />
        <button
          onClick={onClose}
          className="absolute top-2 right-2 bg-white rounded-full p-1 text-gray-700 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
          aria-label="Close image modal"
        >
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>
    </div>
  );
};

// Animated Accordion Content Component
const AccordionContent = ({
  children,
  isOpen,
}: {
  children: React.ReactNode;
  isOpen: boolean;
}) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const style = useSpring({
    from: { height: 0, opacity: 0 },
    to: {
      height: isOpen ? contentRef.current?.scrollHeight || "auto" : 0,
      opacity: isOpen ? 1 : 0,
    },
    config: config.stiff,
  });

  return (
    <animated.div style={{ ...style, overflow: "hidden" }}>
      <div ref={contentRef}>{children}</div>
    </animated.div>
  );
};

// Chevron Component
const Chevron = ({ rotation }: { rotation: number }) => {
  const style = useSpring({
    transform: `rotate(${rotation}deg)`,
    config: { tension: 300, friction: 20 },
  });

  return (
    <animated.div style={style}>
      <ChevronDownIcon className="h-5 w-5 text-gray-500" />
    </animated.div>
  );
};

export const SummaryPanel = ({
  isVisible,
  onSeekTo,
  summaries,
  setSummaries,
  loading,
  generateSummaries,
  videoHash,
}: SummaryPanelProps) => {
  const [expandedSection, setExpandedSection] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalImageUrl, setModalImageUrl] = useState<string | null>(null);
  const [screenshotLoading, setScreenshotLoading] = useState(false);
  const hasAutoGeneratedRef = useRef(false);

  // Regenerate screenshots for existing video
  const regenerateScreenshots = async () => {
    if (!videoHash) {
      setError("Video hash not available");
      return;
    }

    setScreenshotLoading(true);
    setError(null);

    try {
      const response = await fetch(
        `${API_BASE_URL}/regenerate_screenshots/${videoHash}`,
        { method: "POST" }
      );

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(
          errorData.detail || `Failed to regenerate screenshots: ${response.status}`
        );
      }

      const data = await response.json();

      // Update summaries with new screenshot URLs
      if (data.updated_sections && Array.isArray(data.updated_sections)) {
        setSummaries((prevSummaries) =>
          prevSummaries.map((summary) => {
            const updated = data.updated_sections.find(
              (s: { title: string; screenshot_url: string }) =>
                s.title === summary.title
            );
            return updated
              ? { ...summary, screenshot_url: updated.screenshot_url }
              : summary;
          })
        );
      }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to regenerate screenshots"
      );
    } finally {
      setScreenshotLoading(false);
    }
  };

  // List transition animation
  const transitions = useTransition(summaries, {
    from: { opacity: 0, transform: "translate3d(0, 20px, 0)" },
    enter: { opacity: 1, transform: "translate3d(0, 0px, 0)" },
    keys: (item) => item.start + item.end,
    trail: 100, // Stagger effect
  });

  // Auto-generate summaries when panel opens if none exist
  useEffect(() => {
    if (
      isVisible &&
      !summaries.length &&
      !loading &&
      !error &&
      !hasAutoGeneratedRef.current
    ) {
      hasAutoGeneratedRef.current = true;
      generateSummaries();
    }
  }, [isVisible, summaries.length, loading, error, generateSummaries]);

  const handleSeekTo = (time: string) => {
    if (onSeekTo) {
      onSeekTo(time);
    }
  };

  const formatScreenshotUrl = (
    url: string | null | undefined
  ): string | undefined => {
    if (!url) return undefined;

    // If URL already starts with http, return as is
    if (url.startsWith("http")) {
      return url;
    }

    // Otherwise, prepend the API server URL
    return `${API_BASE_URL}${url}`;
  };

  const openImageModal = (imageUrl: string | undefined) => {
    if (imageUrl) {
      setModalImageUrl(imageUrl);
      setIsModalOpen(true);
    }
  };

  if (!isVisible) return null;

  return (
    <div className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden flex flex-col h-full">
      <div className="px-5 py-3 border-b border-gray-200 flex justify-between items-center">
        <h3 className="text-sm font-medium text-gray-800">Content Summary</h3>
        {(!summaries.length || summaries.length > 0) && !loading && !screenshotLoading && (
          <div className="flex gap-2">
            {!summaries.length ? (
              <button
                onClick={generateSummaries}
                className="px-3 py-1 text-xs bg-gray-600 text-white rounded hover:bg-gray-700 transition-colors"
              >
                Generate Summary
              </button>
            ) : (
              <>
                <button
                  onClick={regenerateScreenshots}
                  disabled={!videoHash}
                  className="px-3 py-1 text-xs bg-indigo-600 text-white rounded hover:bg-indigo-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  title={!videoHash ? "Video hash not available" : "Regenerate screenshots from video"}
                >
                  Regenerate Screenshots
                </button>
                <button
                  onClick={generateSummaries}
                  className="px-3 py-1 text-xs bg-gray-600 text-white rounded hover:bg-gray-700 transition-colors"
                >
                  Regenerate Summary
                </button>
              </>
            )}
          </div>
        )}
      </div>

      {loading && (
        <div className="flex flex-col items-center justify-center flex-1 p-8 text-center">
          <div className="inline-block animate-spin h-8 w-8 border-4 border-indigo-500 border-t-transparent rounded-full mb-4"></div>
          <p className="text-gray-900 font-medium">Generating summary...</p>
          <p className="text-sm text-gray-500 mt-1">
            Analyzing video content and extracting key points
          </p>
        </div>
      )}

      {screenshotLoading && (
        <div className="flex flex-col items-center justify-center flex-1 p-8 text-center">
          <div className="inline-block animate-spin h-8 w-8 border-4 border-indigo-500 border-t-transparent rounded-full mb-4"></div>
          <p className="text-gray-900 font-medium">Regenerating screenshots...</p>
          <p className="text-sm text-gray-500 mt-1">
            Extracting frames from video and uploading to storage
          </p>
        </div>
      )}

      {!loading && !screenshotLoading && summaries.length === 0 && !error && (
        <div className="flex flex-col items-center justify-center flex-1 p-8 text-center">
          <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4">
            <svg
              className="w-8 h-8 text-gray-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>
          </div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">
            No Summary Yet
          </h3>
          <p className="text-gray-500 mb-6 max-w-sm">
            Generate a summary to get a quick overview of the key topics and
            segments in this video.
          </p>
          <button
            onClick={generateSummaries}
            className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors font-medium shadow-sm"
          >
            Generate Summary
          </button>
        </div>
      )}

      {error && !loading && (
        <div className="p-4 text-red-600 text-sm">
          {error}
          <button
            className="block mt-2 text-rose-500 hover:text-rose-600"
            onClick={() => setError(null)}
          >
            Dismiss
          </button>
        </div>
      )}

      {!loading && summaries.length > 0 && (
        <div className="divide-y divide-gray-100 overflow-y-auto flex-1">
          {transitions((style, section, _, index) => (
            <animated.div style={style} className="hover:bg-gray-50">
              <div
                className="flex items-start px-5 py-3 cursor-pointer"
                onClick={() =>
                  setExpandedSection(expandedSection === index ? null : index)
                }
              >
                {section.screenshot_url ? (
                  <div className="flex-shrink-0 mr-3">
                    <img
                      src={formatScreenshotUrl(section.screenshot_url)}
                      alt={`Screenshot for ${section.title}`}
                      className="w-32 h-32 object-cover rounded-md shadow-sm hover:shadow-md transition-shadow cursor-pointer"
                      onClick={(e) => {
                        e.stopPropagation();
                        openImageModal(
                          formatScreenshotUrl(section.screenshot_url)
                        );
                      }}
                    />
                  </div>
                ) : (
                  <div className="flex-shrink-0 mr-3 w-32 h-32 bg-gray-100 rounded-md flex items-center justify-center">
                    <span className="text-xs text-gray-400">[No preview]</span>
                  </div>
                )}

                <div className="flex-1">
                  <div className="flex justify-between items-start">
                    <h4 className="text-sm font-medium text-gray-900">
                      {section.title}
                    </h4>
                    <div className="ml-2 flex-shrink-0">
                      <Chevron rotation={expandedSection === index ? 180 : 0} />
                    </div>
                  </div>
                  <p
                    className="mt-1 text-xs text-gray-500 cursor-pointer hover:text-rose-600 hover:underline"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleSeekTo(section.start);
                    }}
                  >
                    {section.start} - {section.end}
                  </p>

                  {/* Collapsed summary preview */}
                  <div
                    className={`mt-1 text-sm text-gray-700 overflow-hidden transition-all duration-300 ${
                      expandedSection === index
                        ? "opacity-0 h-0"
                        : "opacity-100"
                    }`}
                  >
                    <p className="line-clamp-2">{section.summary}</p>
                  </div>
                </div>
              </div>

              <AccordionContent isOpen={expandedSection === index}>
                <div className="px-5 py-2 bg-gray-50">
                  <p className="text-sm text-gray-700">{section.summary}</p>
                  <button
                    className="mt-2 text-xs text-rose-600 hover:text-rose-800"
                    onClick={() => handleSeekTo(section.start)}
                  >
                    Jump to this section
                  </button>
                </div>
              </AccordionContent>
            </animated.div>
          ))}
        </div>
      )}

      {/* Image Modal */}
      {isModalOpen && modalImageUrl && (
        <ImageModal
          imageUrl={modalImageUrl}
          onClose={() => setIsModalOpen(false)}
        />
      )}
    </div>
  );
};
